<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-2QTKDAK" failures="1" tests="1" name="Default test" time="10.597" errors="0" timestamp="2024-04-24T01:50:45 PKT">
  <testcase classname="TestcasePackage.LoginTestClass" name="TestcasetoVerifyLoginwithbothcorrectEmailandPassword" time="0.972">
    <failure type="java.lang.AssertionError" message="The actual and expected links matched expected [https://fnbdev.vteamslabs.com/login] but found [https://fnbdev.vteamslabs.com/dashboard]">
      <![CDATA[java.lang.AssertionError: The actual and expected links matched expected [https://fnbdev.vteamslabs.com/login] but found [https://fnbdev.vteamslabs.com/dashboard]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at TestcasePackage.LoginTestClass.TestcasetoVerifyLoginwithbothcorrectEmailandPassword(LoginTestClass.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestcasetoVerifyLoginwithbothcorrectEmailandPassword -->
  <testcase classname="TestcasePackage.LoginTestClass" name="TestcasetoVerifyLoginwith_CorrectEmailandWrongPassword" time="0.0">
    <ignored/>
  </testcase> <!-- TestcasetoVerifyLoginwith_CorrectEmailandWrongPassword -->
  <testcase classname="TestcasePackage.LoginTestClass" name="TestcasetoVerifyLoginwith_bothWrongEmailandPassword" time="0.0">
    <ignored/>
  </testcase> <!-- TestcasetoVerifyLoginwith_bothWrongEmailandPassword -->
</testsuite> <!-- Default test -->
